# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :development, :test do
  gem 'byebug', '>= 11.1.0'
end

group :development do
  gem 'rubocop', '>= 1.2.0'
  gem 'rubocop-rspec', '>= 2.1.0'
end

group :test do
  gem 'rspec', '~> 3.10.0'
  gem 'guard', '~> 2.16.2'
  gem 'guard-rspec', '~> 4.7.3'
end
